time_intervals:
    
    # [en_US] Time interval to update heroes position in the map,
    # Default value (in minutes): 3
    #
    # [pt_BR] Intervalo de tempo para atualizar a posição dos heróis no mapa
    # Valor padrão (em minutos): 5
    heroes_refresh_position: 1

# [en_US] How confident the bot needs to be to click the buttons (values from 0 to 1. 0 is the minimum value, 1 is the maximum value)
  #
  # [pt_BR] O quão confiante o bot precisa estar para clicar nos botões (valores entre 0 e 1. 0 é o valor mínimo, 1 é o valor máximo)
  #
threshold:
    # [en_US]
    # Default value: 0.7
    #
    # [pt_BR]
    # Valor padrão: 0.7
    default: 0.7